name: SwaggerParserCLI Test

on: [push]

jobs:
  validate_job:
    runs-on: ubuntu-latest
    name: A job to validate a definition
    steps:
      - uses: actions/checkout@v3
      - uses: swagger-api/swagger-parser/.github/actions/@action
        with:
          inputSpec: 'resources/fileWithNoErrorMessages.yaml'
          options: '-resolve -resolveFully'
          serializationType: '-json'
          logsPath: 'resources/parserLogs.yaml'
          parserSpecPath: 'resources/specParsed.json'



