name: SwaggerParserCLI Test

on: [push]

jobs:
  validate_job:
    runs-on: ubuntu-latest
    name: A job to validate a definition
    steps:
      - uses: actions/checkout@v3
      - uses: swagger-api/swagger-parser/.github/actions@action
        with:
          inputSpec: '/home/runner/work/actionTest/actionTest/resources/fileWithNoErrorMessages.yaml'
          options: '-resolve'
          serializationType: '-json'
          logsPath: '/home/runner/work/actionTest/actionTest/resources/parserLogs.yaml'
          parserSpecPath: '/home/runner/work/actionTest/actionTest/resources/specParsed.json'
      - run: cat /home/runner/work/actionTest/actionTest/resources/specParsed.json
        shell: bash



